#!/bin/bash

NAME="vendorMgmt"
DIR=/home/vendorMgmt/vendorMgmt
USER=vendorMgmt
GROUP=vendorMgmt
WORKERS=3
BIND=unix:/home/vendorMgmt/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=vendorMgmt.settings
DJANGO_WSGI_MODULE=vendorMgmt.wsgi
LOG_LEVEL=error

cd $DIR
source ../venv/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec ../venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-