# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(default='$', max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='etype',
            field=models.CharField(choices=[('CONTRACT', 'CONTRACT'), ('SHIPPING', 'SHIPPING'), ('PAYMENT', 'PAYMENT'), ('TAXREFUND', 'TAXREFUND')], max_length=10),
        ),
    ]
