# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20170729_1338'),
        ('event', '0003_event_rmb'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='porder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.POrder'),
        ),
    ]
