# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20170731_0833'),
        ('event', '0004_event_porder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PROFIT', 'PROFIT'), ('COST', 'COST')], max_length=10)),
                ('ctype', models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('LOGISTICS', 'LOGISTICS'), ('POSTING', 'POSTING'), ('SALES', 'SALES'), ('TAXREFUND', 'TAXREFUND'), ('EXTRA', 'EXTRA')], max_length=50)),
                ('cost', models.IntegerField()),
                ('receipt', models.BooleanField(default=True)),
                ('happen_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('porder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.POrder')),
            ],
        ),
    ]
