# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_auto_20170718_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='total_demand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supply',
            name='demand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allocation.Demand'),
        ),
    ]
