# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0004_auto_20170721_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='month',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='year',
        ),
    ]
