# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_auto_20170723_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')]),
        ),
        migrations.AlterField(
            model_name='demand',
            name='total_demand',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='demand',
            name='year',
            field=models.PositiveIntegerField(choices=[(2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')]),
        ),
        migrations.AlterField(
            model_name='demandclient',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='supply',
            name='total_supply',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplyvendor',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
