# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0006_auto_20170723_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyvendor',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
