# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20170723_1352'),
        ('allocation', '0007_auto_20170723_0903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplyvendor',
            unique_together=set([('supply', 'vendor')]),
        ),
    ]
