# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porder',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='porder',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='porder',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
