# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20170723_1352'),
        ('order', '0002_auto_20170725_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(choices=[('POWDER', 'POWDER'), ('GRANULAR', 'GRANULAR'), ('LIQUID', 'LIQUID')], default='POWDER', max_length=10)),
                ('num', models.PositiveIntegerField()),
                ('packing_type', models.CharField(choices=[('CARTON', 'CARTON'), ('BAG', 'BAG'), ('DRUM', 'DRUM'), ('CYLINDER', 'CYLINDER'), ('EXTRA', 'EXTRA')], default='BAG', max_length=10)),
                ('unit_weight', models.IntegerField()),
                ('pallet_weight', models.IntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packingproduct', to='products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='porderitem',
            name='packing_type',
        ),
        migrations.RemoveField(
            model_name='porderitem',
            name='pallet_weight',
        ),
        migrations.RemoveField(
            model_name='porderitem',
            name='unit_weight',
        ),
        migrations.AddField(
            model_name='porderitem',
            name='packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Packing'),
        ),
        migrations.AlterUniqueTogether(
            name='packing',
            unique_together=set([('product', 'ptype', 'num')]),
        ),
    ]
