# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20170726_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.SalesOrder'),
        ),
    ]
