# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20170726_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='porder',
            name='contract_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
