# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20170727_0235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porder',
            options={'ordering': ('-contract_date',)},
        ),
        migrations.RemoveField(
            model_name='porderitem',
            name='quotation',
        ),
    ]
