# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20170729_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesContract', models.FileField(blank=True, null=True, upload_to='')),
                ('purchaseContract', models.FileField(blank=True, null=True, upload_to='')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='')),
                ('packingList', models.FileField(blank=True, null=True, upload_to='')),
                ('billofLading', models.FileField(blank=True, null=True, upload_to='')),
                ('coa', models.FileField(blank=True, null=True, upload_to='')),
                ('fta_co', models.FileField(blank=True, null=True, upload_to='')),
                ('baoguandan', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('porder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.POrder')),
            ],
        ),
    ]
