# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='porder',
        ),
        migrations.RemoveField(
            model_name='material',
            name='purchaseContract',
        ),
        migrations.RemoveField(
            model_name='material',
            name='salesContract',
        ),
        migrations.AddField(
            model_name='material',
            name='shipping',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Shipping'),
        ),
        migrations.AddField(
            model_name='porder',
            name='purchase_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='porder',
            name='sales_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
