# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20170731_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='baoguandan',
            field=models.FileField(blank=True, null=True, upload_to='material/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='billofLading',
            field=models.FileField(blank=True, null=True, upload_to='material/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='coa',
            field=models.FileField(blank=True, null=True, upload_to='material/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='fta_co',
            field=models.FileField(blank=True, null=True, upload_to='material/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='material/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='packingList',
            field=models.FileField(blank=True, null=True, upload_to='material/%Y/%m/'),
        ),
    ]
