# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170707_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sourcing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmbprice', models.FloatField()),
                ('usdprice', models.FloatField(blank=True, null=True)),
                ('payterm', models.CharField(choices=[('CACHE', 'CACHE'), ('30%PREPAY, 70%LATER', '30%PREPAY, 70%LATER'), ('T/T 30 DAYS', 'T/T 30 DAYS'), ('T/T 45 DAYS', 'T/T 45 DAYS'), ('T/T 60 DAYS', 'T/T 60 DAYS'), ('T/T 90 DAYS', 'T/T 90 DAYS')], default='T/T 60 DAYS', max_length=20)),
                ('quote_date', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('V', 'VALID'), ('I', 'IN-VALID')], default='V', max_length=1)),
                ('comments', models.TextField(blank=True, null=True)),
                ('vendorproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.VendorProduct')),
            ],
            options={
                'ordering': ['-status', '-quote_date'],
            },
        ),
    ]
