# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170708_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_type', models.CharField(choices=[('CARTON', 'CARTON'), ('BAG', 'BAG'), ('DRUM', 'DRUM'), ('EXTRA', 'EXTRA')], default='BAG', max_length=10)),
                ('unit_weight', models.IntegerField()),
                ('pallet_weight', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='quotation',
            name='payterm',
            field=models.CharField(choices=[('CASH', 'CASH'), ('30%PREPAY, 70%LATER', '30%PREPAY, 70%LATER'), ('T/T 30 DAYS', 'T/T 30 DAYS'), ('T/T 45 DAYS', 'T/T 45 DAYS'), ('T/T 60 DAYS', 'T/T 60 DAYS'), ('T/T 90 DAYS', 'T/T 90 DAYS')], default='T/T 60 DAYS', max_length=20),
        ),
        migrations.AlterField(
            model_name='sourcing',
            name='payterm',
            field=models.CharField(choices=[('CASH', 'CASH'), ('30%PREPAY, 70%LATER', '30%PREPAY, 70%LATER'), ('T/T 30 DAYS', 'T/T 30 DAYS'), ('T/T 45 DAYS', 'T/T 45 DAYS'), ('T/T 60 DAYS', 'T/T 60 DAYS'), ('T/T 90 DAYS', 'T/T 90 DAYS')], default='CASH', max_length=20),
        ),
    ]
