# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_packing_ptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='packing_type',
            field=models.CharField(choices=[('CARTON', 'CARTON'), ('BAG', 'BAG'), ('DRUM', 'DRUM'), ('CYLINDER', 'CYLINDER'), ('EXTRA', 'EXTRA')], default='BAG', max_length=10),
        ),
        migrations.AlterField(
            model_name='packing',
            name='pallet_weight',
            field=models.IntegerField(default=500),
        ),
    ]
