# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170711_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['vendorproduct', '-status', '-quote_date']},
        ),
    ]
