# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170718_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=20)),
                ('cn_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Location'),
        ),
    ]
