# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170718_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
