# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_vendor_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['en_name']},
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
