# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170718_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['en_name']},
        ),
        migrations.RenameField(
            model_name='sourcing',
            old_name='sales_price',
            new_name='usd_price',
        ),
    ]
