# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20170719_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcing',
            name='sales_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
