# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20170721_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['cn_name']},
        ),
    ]
