# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20170723_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cas_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CAS NO'),
        ),
    ]
