# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20170727_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['en_name']},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['status', 'price']},
        ),
        migrations.AddField(
            model_name='vendor',
            name='product_list',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
