# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20170822_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='product_list',
            field=models.FileField(blank=True, null=True, upload_to='product_list/'),
        ),
    ]
