# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20170823_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcing',
            old_name='sales_price',
            new_name='saller_usd_price',
        ),
    ]
