# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20170830_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcing',
            name='buying_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcing',
            name='saller_usd_price',
            field=models.FloatField(blank=True, null=True, verbose_name='SELLER EXPORT PRICE'),
        ),
    ]
