# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20170830_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='birthyear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='capital',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sales_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
