# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20170905_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='companytype',
            field=models.CharField(choices=[('TRADING', 'TRADING'), ('MANUFACTURER', 'MANUFACTURER'), ('MIXING', 'MIXING')], default='MANUFACTURER', max_length=20),
        ),
    ]
